default_env: &default
  adapter: postgresql
  encoding: unicode
  database: s_WUE

development:
  <<: *default

production:
  <<: *default
  
  host: dpg-ck38at36fquc7390vjp0-a
  database: s_original_uc87
  username: s_original_uc87_user
  password: aKYSO5XRpxLRjYUk6V0ZniHGzmsSe0Rb
